

DROP TABLE IF EXISTS metro_dw.SALE;
DROP TABLE IF EXISTS metro_dw.PRODUCT;
DROP TABLE IF EXISTS metro_dw.CUSTOMER;
DROP TABLE IF EXISTS metro_dw.SUPPLIER;
DROP TABLE IF EXISTS metro_dw.TDATE;
DROP TABLE IF EXISTS metro_dw.STORE;


DROP SCHEMA IF EXISTS metro_dw;


CREATE SCHEMA metro_dw;

CREATE TABLE metro_dw.CUSTOMER(
	CUSTOMER_ID varchar(4) not null,
    CUSTOMER_NAME varchar(30),
	PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE metro_dw.PRODUCT(
	PRODUCT_ID varchar(6) not null,
    PRODUCT_NAME varchar(30),
	PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE metro_dw.SUPPLIER(
	SUPPLIER_ID varchar(5) not null,
    SUPPLIER_NAME varchar(30),
	PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE metro_dw.STORE(
	STORE_ID varchar(4) not null,
    STORE_NAME varchar(20),
	PRIMARY KEY (STORE_ID)
);


CREATE TABLE metro_dw.TDATE(
	TDATE_ID DATE not null,
    T_DAY int,
	T_DAYOFWEEK int,
    T_MONTH int,
	T_QUARTER int,
    T_YEAR int,
	PRIMARY KEY (TDATE_ID)
);

CREATE TABLE metro_dw.SALE(
	TRANSACTION_ID varchar(8) not null,
    CUSTOMER_ID varchar(4) not null,
    PRODUCT_ID varchar(6) not null,
    SUPPLIER_ID varchar(5) not null,
	STORE_ID varchar(4) not null,
    TDATE_ID DATE not null,
    QUATITY INTEGER(3),
    PRICE DECIMAL(5,2) DEFAULT(0.0),
	TOTAL_SALE DECIMAL(10,2) DEFAULT(0.0),
	
	FOREIGN KEY (CUSTOMER_ID) REFERENCES metro_dw.CUSTOMER(CUSTOMER_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES metro_dw.PRODUCT(PRODUCT_ID),
	FOREIGN KEY (SUPPLIER_ID) REFERENCES metro_dw.SUPPLIER(SUPPLIER_ID),
	FOREIGN KEY (STORE_ID) REFERENCES metro_dw.STORE(STORE_ID),
	FOREIGN KEY (TDATE_ID) REFERENCES metro_dw.TDATE(TDATE_ID),
	
	PRIMARY KEY (TRANSACTION_ID, CUSTOMER_ID, PRODUCT_ID, SUPPLIER_ID, STORE_ID, TDATE_ID)
	
	
);








DELIMITER $$
CREATE PROCEDURE metro_dw.INSERT_PRODUCT(IN PRODUCT_ID varchar(6), IN PRODUCT_Name varchar(30))
BEGIN

	DECLARE EXIT HANDLER FOR 1062
	BEGIN
	END;

	INSERT INTO metro_dw.PRODUCT
	VALUES  (PRODUCT_ID, PRODUCT_NAME);

END$$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE metro_dw.INSERT_CUSTOMER(IN CUSTOMER_ID varchar(4), IN CUSTOMER_Name varchar(30))
BEGIN

	DECLARE EXIT HANDLER FOR 1062
	BEGIN
	END;

	INSERT INTO metro_dw.CUSTOMER
	VALUES  (CUSTOMER_ID, CUSTOMER_NAME);

END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE metro_dw.INSERT_SUPPLIER(IN SUPPLIER_ID varchar(5), IN SUPPLIER_Name varchar(30))
BEGIN

	DECLARE EXIT HANDLER FOR 1062
	BEGIN
	END;

	INSERT INTO metro_dw.SUPPLIER
	VALUES  (SUPPLIER_ID, SUPPLIER_NAME);

END$$
DELIMITER ;



DELIMITER $$
CREATE PROCEDURE metro_dw.INSERT_STORE(IN STORE_ID varchar(4), IN STORE_Name varchar(20))
BEGIN

	DECLARE EXIT HANDLER FOR 1062
	BEGIN
	END;

	INSERT INTO metro_dw.STORE
	VALUES  (STORE_ID, STORE_NAME);

END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE metro_dw.INSERT_TDATE(IN TDATE_ID DATE, IN DD int, IN DOW int, IN MM int, IN QT int, IN YYYY int)
BEGIN

	DECLARE EXIT HANDLER FOR 1062
	BEGIN
	END;

	INSERT INTO metro_dw.TDATE
	VALUES  (TDATE_ID, DD, DOW, MM, QT, YYYY);

END$$
DELIMITER ;

